### PR TITLE
Updates to "Adobe XD" section

### PR DESCRIPTION
**Pull request by marionnegp**
## What I did

Updated wording on the [Design system kit page](https://ux.redhat.com/get-started/design-system-kit/) about how to get a license and where kit is maintained

### CODE REVIEW

**Comment by marionnegp** [comment]
Something I noticed in the deploy preview is that `Design system kit` is in a different spot in the sidebar. Why would this have moved?

**Live ux.redhat.com**
Screen Shot 2022-05-18 at 3 49 09 PM


**Deploy preview**
Screen Shot 2022-05-18 at 3 49 02 PM

**Comment by bennypowers** [comment]
@marionnegp got you covered 🙌

**Review by bennypowers — APPROVED** [review]
Licenses? Gosh, Too Much!

**Comment by marionnegp** [comment]
Haha, thanks, @bennypowers!

**Pull request merged**
