### PR TITLE
docs: optimize patterns svg

### LINKED ISSUE #1119: [docs]: some SVGs double scaled in patterns folder
Some SVG files in the patterns folder are double scaled from what their rendered form should be.  ~~When used in an example shortcode this then makes the image larger then it should be.~~. This is more likely a function of export settings.  

Need to rescale these images to the appropriate rendered size. 

We can replace these by PNGs if necessary, @coreyvickery has mentioned issues with exporting from SVGs from XD.

Images scaled up 2x at render: 

- [x] https://ux.redhat.com/patterns/disclosure/#mobile
- [x] https://ux.redhat.com/patterns/sticky-card/#style
- [x] https://ux.redhat.com/patterns/sticky-card/#content

### PR DESCRIPTION
**Pull request by bennypowers**
Fixes #1119 

## What I did

1. ran svgo on all the graphics in `docs/patterns/*/*.svg` using this config:

<details><summary>svgo.config.js</summary>

```js
module.exports = {
  multipass: true, // boolean. false by default
  // datauri: 'enc', // 'base64' (default), 'enc' or 'unenc'.
  pretty: true,
  js2svg: {
    indent: 2, // string with spaces or number of spaces. 4 by default
    pretty: true, // boolean, false by default
  },
  plugins: [
    // set of built-in plugins enabled by default
    {
      name: 'preset-default',
      params: {
        overrides: {
          removeTitle: false,
        },
      },
    },

    // enable built-in plugins by name
    'prefixIds',

    'cleanupIds',

    'cleanupAttrs',

    'convertStyleToAttrs',

    'removeDimensions',

    // or by expanded notation which allows to configure plugin
    {
      name: 'sortAttrs',
      params: {
        xmlnsOrder: 'alphabetical',
      },
    },
  ],
};
```

</details>

## Testing Instructions

1. check the DP for those particular pages (cc @zeroedin )

### CODE REVIEW

**Review by zeroedin — COMMENTED** [review]
Any harm in adding svgo process to the standard build? IIRC svgo will not really recompress a svg unless it has the additional meta data not needed for browser rendering.  Other options I guess could be adding a `*.min.svg` to files that have been compressed , or just compressing them on copy to `_site` directory?

**Comment by coreyvickery** [comment]
@brianferry What is left to be done for this?

**Comment by brianferry** [comment]
@coreyvickery - Not sure the current status with this PR, we saw that it was linked to by #1221 which caused it to close the PR prematurely.  1221 was optimizing `sticky card` and `disclosure` specifically whereas this is a site-wide enhancement of the svgs under the `patterns` directory.

**Comment by zeroedin** [comment]
@bennypowers is this PR outdated at this point enough to just be closed?  #1119 as originally stated was more about the images scaled size.  The svgo optimization IIRC did not seem to fix that issue specifically. @coreyvickery regenerated those images as pngs instead in  #1221 which on merge accidentally was linked to this PR to closed it instead of the issue.

Do we need an general svgo optimization task on ci builds?

**Pull request closed without merging**
