### PR TITLE
feat(card): lighter and darker palettes

### PR DESCRIPTION
**Pull request by bennypowers**
## What I did

1. add lighter and darker palettes to card
2. add `allow="lighter,darker,..."` attr to context picker helper element
3. adjust whitespace of card parts (header, body, footer) to suit designs
4. update card demos to match

## Notes to Reviewers

Please merge #1326  first if there are conflicts here after merging that, i'll resolve them

### CODE REVIEW

**Review by marionnegp — COMMENTED** [review]
The context picker is updating the card colors as expected. Are the styles below for the header still available?

Screenshot 2023-11-14 at 12 58 34 PM
Screenshot 2023-11-14 at 12 58 31 PM

**Comment by bennypowers** [comment]
@marionnegp  https://deploy-preview-1327--red-hat-design-system.netlify.app/elements/card/demo/color-context/

**Comment by bennypowers** [comment]
but please merge #1326  first

**Review by marionnegp — APPROVED** [review]
Nice, thanks!

**Pull request merged**
