### PR TITLE
Adding roadmap page and aligning shared styles with release notes

### PR DESCRIPTION
**Pull request by markcaron**
## What I did

1. Added Roadmap page under About
2. Moved shared styles out of Release Notes into Styles.scss
3. Cleaned up Roadmap and Release Notes feedback sections

### CODE REVIEW

**Comment by hellogreg** [comment]
Don't know if you're okay with having the external Feedback link icon orphaned in the widest Chrome/Safari/Firefox desktop view:
orphaned icon in Feedback section

**Comment by hellogreg** [comment]
The page has two elements with `id="roadmap"`:
duplicate roadmap

**Comment by hellogreg** [comment]
The "release notes" link points right back to this roadmap page:
release notes section and link

**Review by hellogreg — APPROVED** [review]
lgtm!

**Comment by markcaron** [comment]
@hellogreg @zeroedin fixed. updated.

**Review by zeroedin — APPROVED** [review]

**Pull request merged**
