### PR TITLE
fix(tabs): vertical tabs display as horizontal on small screens

### LINKED ISSUE #940: [bug] <rh-tabs>: vertical styles at mobile screen size.
### Describe the bug

`<rh-tabs vertical>` Vertical tabs do not have great mobile experience.  In prior documentation we suggested to not use vertical tabs on a mobile experience.  This came up again in #933 and #867.  

However now that tabs has a mobile experience baked in with horizontal scrolling we should maybe auto convert `vertical` tabs to a horizontal tabs style when under a mobile sized breakpoint thus gaining the scroll feature.

We will need to determine at what breakpoint `vertical` tabs display back as vertical.  My assumption is this is most likely at`(min-width: 768px)` would be acceptable.

### Which Component?

rh-tabs

### Steps to reproduce

View the demo on a mobile screen at: https://ux.redhat.com/elements/tabs/demo/

### Expected behaviour

Vertical tabs should look like horizontal tabs and scroll on small screens

### Screenshots

_No response_

### Element HTML

_No response_

### Operating System (OS)

iOS

### Browser

Chrome

### More browser information

_No response_

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by zeroedin**
## What I did

1.  Vertical tabs at screen sizes less than `768px` will now display as if they were a horizontal tab.

Closes #940

## TODO

- [x] Fix padding on `[vertical]` tabs tab in horizontal / mobile mode.  

## Testing Instructions

1. View [deploy preview](https://deploy-preview-1042--red-hat-design-system.netlify.app/elements/tabs/demo/)
2. View [color-context demo](https://deploy-preview-1042--red-hat-design-system.netlify.app/elements/tabs/demo/color-context/)

## Notes to Reviewers
This was a pretty sizable modification to the CSS.  Please look for any regressions in look and feel.  Will have to look carefully at the DP and `ux.` to compare looking for stylistic regressions across all tab variations. Vertical tabs should switch to horizontal on small screens `< 768px` as well as maintain correct borders even under context changes.

@bennypowers my assumption this at least qualifies for a "minor" change, wanted to discuss before creating a changeset.

### CODE REVIEW

**Comment by bennypowers** [comment]
CSS changes are kind of a judgement call. One could make the argument that this is a major. We should get a list of real world uses and check against them

**Review by coreyvickery — APPROVED** [review]
Looks good.

**Comment by zeroedin** [comment]
> CSS changes are kind of a judgement call. One could make the argument that this is a major. We should get a list of real world uses and check against them

On hold till we resolve changeset level. 

A question remaining will be [the documentation](https://deploy-preview-965--red-hat-design-system.netlify.app/elements/tabs/guidelines/#small-breakpoints) suggests this swap between vertical and mobile happens.  Until this PR merges it does not (assuming a much longer hold if a "major" change).  Do we hold the docs PR as well?  Thoughts? /cc @bennypowers @coreyvickery

**Comment by coreyvickery** [comment]
@zeroedin I guess I can hide mention of responsive vertical tabs until this is worked out, I want to avoid further delaying the release of this new doc page.

**Comment by bennypowers** [comment]
if the docs say (now and at release) that the behaviour in this pr is supposed to happen, and it doesn't currently, then this PR is a patch, not a major

**Comment by zeroedin** [comment]
> if the docs say (now and at 1.0 release)

This is part of the issue tabs at 1.0 did not have docs specifically to the new feature set.  Our docs on `ux.` were hold overs from PFE tabs:

> Mobile

> Tabs can’t be used on screens that are less than 576px wide because the limited space will cause too many section text labels to get cut off. In this environment, tabs will convert to an accordion.

**Comment by bennypowers** [comment]
if you can test all the specific in-the-wild uses, then we can probably get away with a patch commit, but don't make a habit of it :)

**Pull request merged**
