### PR TITLE
docs: add Get Started: Designers page

### PR DESCRIPTION
**Pull request by marionnegp**
## What I did

Added Get started: Designers page

## Testing Instructions

Review the [Designers](https://deploy-preview-1401--red-hat-design-system.netlify.app/get-started/designers/) page in the DP.

## Notes to Reviewers
- I changed "send us an e-mail" to "e-mail design-system@redhat.com", so users could see the email address without having to click the link and open their mail app.

### CODE REVIEW

**Review by coreyvickery — CHANGES_REQUESTED** [review]
@marionnegp Will you be removing the other pages in the section?

**Comment by marionnegp** [comment]
> @marionnegp Will you be removing the other pages in the section?

I deleted the "Icon libraries" and "Product logo library" pages. I can add updating the "Overview" page to #1176 if you think it's worth keeping.

**Comment by coreyvickery** [comment]
> I can add updating the "Overview" page to #1176 if you think it's worth keeping.

@marionnegp That page is also severely outdated. Let's remove.

**Comment by marionnegp** [comment]
@coreyvickery, we discussed keeping the Get Started: Overview page during today's office hours. Other sections have landing pages, and if the left menu doesn't load, we could still have somewhere to link people. I can work on a mockup for this and will open a new PR. Is the Designers page good to go otherwise?

**Review by coreyvickery — APPROVED** [review]
Looks great.

**Pull request merged**
