### PR TITLE
docs: add danger icon to the best practices example container

### LINKED ISSUE #916: [docs] Add icon to best practices example container
Need to add the exclamation mark in a red circle to the CSS for best practices.
Screenshot 2023-04-12 at 10 54 57 AM

- Icon size: 24px
- Spacing from top left corner: 8px

The CSS class that's pulling in the border and transparent bg is `.example--palette-wrong2`.

### PR DESCRIPTION
**Pull request by marionnegp**
## What I did

1. Uploaded danger icon SVG to assets folder
2. Added it as a background image for the best practices example containers

Note that this will change the style for all best practices examples across the site.

## Testing Instructions

Visit an element page in the deploy preview and view an example under "Best practices" section. (The [Alert page](https://deploy-preview-917--red-hat-design-system.netlify.app/elements/alert/) has some at the bottom of the "Overview" tab.)

## Notes to Reviewers
Closes #916

### CODE REVIEW

**Comment by coreyvickery** [comment]
@marionnegp Do you know how to globally change the `border-radius` of all cards to 0.5rem (8px) in the CSS? Maybe that should be a new issue.

**Comment by marionnegp** [comment]
@coreyvickery, yeah, that would be updated in the same file if you're talking about updating just the docs example cards. Probably should be a different issue/PR since other cards would be affected.

**Comment by coreyvickery** [comment]
@marionnegp Okay, let's hold off for now.

**Review by coreyvickery — APPROVED** [review]
Looks good.

**Pull request merged**
