### PR TITLE
fix(card): adding thumbnail slot, header styling for image / header combo

### PR DESCRIPTION
**Pull request by brianferry**
## What I did

1.  Added a thumbnail slot to the rh-card component so that users can have both the thumbnail image and an heading tag insider of the `<header>` block in the shadowdom. 
2. Styled the header block so that the image and the header (if they're both present) stack vertically.

### CODE REVIEW

**Comment by brianferry** [comment]
@coreyvickery @marionnegp 

Need some feedback here with regards to the header sizing.  Not currently limiting the header image size here to give room for the image and the header tag.  Not sure if there should be a hard limit on that image size.

@nikkimk @hellogreg 

Both the thumbnail image and the heading tag are in the <header> block which seems okay but wasn't sure if the placement of these would cause any problems? (Image tag above heading tag)

**Comment by hellogreg** [comment]
> Both the thumbnail image and the heading tag are in the block which seems okay but wasn't sure if the placement of these would cause any problems? (Image tag above heading tag)

If the image is non-decorative (i.e., needs `alt` text), I think you'd ideally want it to be after its associated heading in the source, even if it's first visually. That way users of assistive tech navigating by headings will experience it as part of that section. (In other words, if the image comes before the heading, a screen reader user may never know it's there.)

This is a case where the logical reading order doesn't necessarily match the visual reading order.

[W3C WAI tip example](https://www.w3.org/WAI/tips/developing/#reflect-the-reading-order-in-the-code-order)

Where it gets tricky is if both the image and the heading are links (as I know has been done when implementing cards in the past, and maybe present). Then visual focus order could be moving in an unexpected direction: tab focus moving up from the heading to the image. But I think we really shouldn't be having two or three links (image, heading, and CTA) to the same destination in cards anyway.

**Comment by marionnegp** [comment]
@coreyvickery @brianferry, I'm not sure if we need a hard limit on the image size. Might be better to add guidelines to documentation if we need to make a recommendation.

**Comment by bennypowers** [comment]
is it possible to do this without adding or removing a new slot name?

**Comment by brianferry** [comment]
> is it possible to do this without adding or removing a new slot name?

We can instruct the user to include both their image and heading element in the header slot and update the css to show all the items in the header.  Then update our .full pattern css to include the styles needed.  

Pretty minor changes with that method

**Review by bennypowers — APPROVED** [review]
Nice, minimal change that gets the job done :)

**Comment by bennypowers** [comment]
@diwanshi does this address your issue in #1205 ?

**Comment by diwanshi** [comment]
@bennypowers @brianferry yes that works for us.

**Comment by bennypowers** [comment]
@brianferry can you add a patch changeset? Then we're good to merge

**Comment by brianferry** [comment]
@bennypowers added

**Pull request merged**
