### PR TITLE
fix(accordion): Remove BaseAccordion dependency

### PR DESCRIPTION
**Pull request by bennypowers**
## What I did

1. remove `heading-tag` and `heading-text` from accordion header
2. only generate shadow header if one is not slotted in
3. use heading level controller for that
4. remove BaseAccordionHeader
5. make AccordionHeaderChangeEvent a cancellable Event

## Testing Instructions

1. the usual

### CODE REVIEW

**Comment by bennypowers** [comment]
@zeroedin some preliminary work ahead of the controller stuff from pfe

**Comment by bennypowers** [comment]
@zeroedin what are the chances on this one? would we rather reimplemlent for now, then circle back if-and-when there's a controller available?

**Comment by zeroedin** [comment]
> @zeroedin what are the chances on this one? would we rather reimplemlent for now, then circle back if-and-when there's a controller available?

I think the reimplementation is fine for now, we dont have a controller that is abstract enough.  I'll give this a once over as is.

**Comment by markcaron** [comment]
@bennypowers let's do this in Charmander

**Comment by markcaron** [comment]
@bennypowers isn't this getting resolved in Charmander? Do we need to close this PR?

**Comment by zeroedin** [comment]
> @bennypowers isn't this getting resolved in Charmander? Do we need to close this PR?
> 
> CC: @zeroedin

This PR needs to be resolved/merged before PF4.0 is brought in as a dependency as it removes the BaseAccordion class.  I'll take a look at it tomorrow and see if I can't get it over the hump.

**Comment by zeroedin** [comment]
Closing this PR as stale and outdated.  `<rh-accordion>` already doesn't require `BaseAccordion` from pfe.

Example `RhAccordion extends LitElement` on staging/charmander
https://github.com/RedHat-UX/red-hat-design-system/blob/68b860257dcbd3b483b894092c1a2a17e6365bd9/elements/rh-accordion/rh-accordion.ts#L61

**Pull request closed without merging**
