### PR TITLE
docs: sidenav/subnav active page

### LINKED ISSUE #1306: [bug][docs] `<rh-subnav>` items on elements' pages don't set current page state on side nav (except for Overview)
The "tabs" in Subnavigation on elements' pages do not set current page state on the side nav, except for Overview.

image

### PR DESCRIPTION
**Pull request by bennypowers**
Closes #1306 

## What I did

1. simplify navigation HTML, CSS, JS
2. de-sassify and de-bem-ify nav css
3. apply active style to pages with a subnav

## Testing Instructions

1. don't forget mobile breakpoints

### CODE REVIEW

**Comment by nikkimk** [comment]
@bennypowers side nav for Patterns is not visible: https://deploy-preview-1307--red-hat-design-system.netlify.app/patterns/

**Comment by bennypowers** [comment]
Thanks @nikkimk PTAL

wrt tokens search: :shrug: 
image

**Comment by bennypowers** [comment]
image

**Review by nikkimk — APPROVED** [review]
Luggage gets tagged meticulously

**Pull request merged**
