### PR TITLE
docs: typography status table

### LINKED ISSUE #554: [bug] ux.redhat.com/foundations/typography/
### Describe the bug

Typography availability section is blank

### Which Component?

n/a

### Steps to reproduce

1. Go to https://ux.redhat.com/foundations/typography/
2. View blank section for Typography availibility

### Expected behaviour

Visible table

### Screenshots

Screen Shot 2022-09-29 at 9 20 07 PM

### Element HTML

_No response_

### Operating System (OS)

macOS

### Browser

Chrome

### More browser information

_No response_

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by bennypowers**
Closes #554 

## What I did

1. Replace old web-component table with csv based

## Testing Instructions

1. `npm run build && npm run watch:docs`

## Notes to Reviewers

Currently, the "Typography" row is missing from the csv data, so the whole section is not displayed. Adding rows that start with `Typography - ` to the csv file will cause the table to render

### CODE REVIEW

**Comment by bennypowers** [comment]
So @RedHat-UX/designers go ahead and add the rows, this can merge today if the data's available. just make sure the changes to the csv file _only affect the added rows_ i.e. no extraneous formatting changes

**Comment by bennypowers** [comment]
yes

**Comment by coreyvickery** [comment]
@bennypowers Will this method still allow us the ability to add special formatting to tables? When we start adding design tokens pages to ux dot, they will need tables with special formatting capabilities.

**Comment by marionnegp** [comment]
Are we pulling the fonts from https://github.com/RedHatOfficial/RedHatFont? If so, do we still need the table?

**Comment by coreyvickery** [comment]
@bennypowers What is the status of this?

**Comment by bennypowers** [comment]
same as before, if design teammates add typography rows to the csv, they will appear on the page, if not, the table will not appear on the page

**Comment by coreyvickery** [comment]
@bennypowers Can we close this?

**Comment by bennypowers** [comment]
@coreyvickery has #554 been resolved to your satisfaction? If so, we can close this PR.

**Review by coreyvickery — APPROVED** [review]

**Pull request closed without merging**
