### PR TITLE
docs(accordion): add information about accent slot

### LINKED ISSUE #1539: [docs] `<rh-accordion>`: add info about accent slot
Add info about accent slot that was added in #1505

### PR DESCRIPTION
**Pull request by marionnegp**
## What I did

1. Updated the Style and Guideline subpages with info about accent slot

## Testing Instructions

Check the following sections for new info:
- Style: [Anatomy](https://deploy-preview-1564--red-hat-design-system.netlify.app/elements/accordion/style/#anatomy)
- Style: [Space](https://deploy-preview-1564--red-hat-design-system.netlify.app/elements/accordion/style/#space)
- Style: [Configuration](https://deploy-preview-1564--red-hat-design-system.netlify.app/elements/accordion/style/#accent-slot) 

## Notes to Reviewers
Closes #1539

### CODE REVIEW

**Comment by coreyvickery** [comment]
@marionnegp Looks great. The only thing I don't see is the spacing value in between the tags and heading.

**Comment by coreyvickery** [comment]
@marionnegp Sorry, I meant when the tags are UNDER the heading. I see specs for when they are on the right.

**Comment by marionnegp** [comment]
@coreyvickery, added it. Can you re-check the page?

**Comment by coreyvickery** [comment]
@marionnegp Approved.

**Comment by marionnegp** [comment]
@coreyvickery, can you approve the PR under the "Files changed" tab? It won't let me merge changes without it.

**Review by coreyvickery — APPROVED** [review]

**Pull request merged**
