### PR TITLE
docs(table): markup guidance

### PR DESCRIPTION
**Pull request by markcaron**
Picking up where we left off on https://github.com/RedHat-UX/red-hat-design-system/pull/1284

### CODE REVIEW

**Review by nikkimk — CHANGES_REQUESTED** [review]
My bad. URL in warning needs to be fixed.

**Review by nikkimk — APPROVED** [review]
Limerick gets too mature

**Review by hellogreg — APPROVED** [review]
Lysistrata's Greek Tale Meanders

**Comment by brianferry** [comment]
@markcaron attempted to resolve conflicts for the 40-accessibility.md page, can you please take a look and make sure it looks correct?

**Comment by markcaron** [comment]
@brianferry Looks good still.

**Pull request merged**
