### PR TITLE
docs(playground): add live coding playgrounds to component pages

### PR DESCRIPTION
**Pull request by bennypowers**
## What I did

1. Add Playground Elements over unpkg CDN (recommended to load from a separate origin for security)
2. Add a `playground` 11ty shortcode for component pages
3. Apply that shortcode to the footer page

image

## Testing Instructions

1. https://deploy-preview-467--red-hat-design-system.netlify.app/components/footer#demo

### CODE REVIEW

**Comment by bennypowers** [comment]
blocked by https://github.com/patternfly/patternfly-elements/pull/2136

**Comment by bennypowers** [comment]
Huge thanks to @heyMP, @brianferry, and @zeroedin for their help debugging playground module resolution issues.

**Comment by bennypowers** [comment]
@RedHat-UX/designers ready for review. Anything not critical can we spin out into a new issue?

**Comment by coreyvickery** [comment]
@bennypowers There is nothing under the `Demo` heading to click on.

**Comment by bennypowers** [comment]
@coreyvickery which brower are you using?

**Comment by coreyvickery** [comment]
@bennypowers Latest version of Chrome.

**Comment by coreyvickery** [comment]
@bennypowers Latest version of Chrome.

**Comment by bennypowers** [comment]
image
runs fine for me in ff, chromium, and webkit. perhaps you need to clear cache?

**Comment by bennypowers** [comment]
this pr only implements it on footer, subsequent prs will do each component page one by one, and the ia will shake everything up, but this technology will be a part of the new pages once we're ready to build out the new ia

**Review by marionnegp — COMMENTED** [review]
No critical edits from me. Here are some that can be addressed in another PR:

- Add some spacing (maybe 24px) above “Result” and make “Result” an h3 or bold it
- I don’t think you need the light gray border above the demo result
- Adding a light gray background to the code block might help users see the boundaries of the iframe. #F5F5F5 should provide enough contrast.

**Comment by coreyvickery** [comment]
@markcaron Would like your opinion about adding this to the website for footer only.

**Comment by markcaron** [comment]
I think with a little design love (as @marionnegp mentions) and use of our `<rh-tabs>`, this is a great feature.

We start with the footer for now and/or apply it to the new IA component templates. Whichever comes first.

Also, I like the concept of "Broducts" (in the main description and footer) 😅

**Comment by bennypowers** [comment]
can we merge this, start the process of adding it to other component pages, and iterate on the design?

**Comment by bennypowers** [comment]
@heyMP can you double check the merge to rh-footer demo?

**Comment by bennypowers** [comment]
Netlify builds were failing. I fixed that by updating the pfe-tools dependency. WDYT, can we merge as is and iterate on the design in subsequent PRs? @marionnegp @markcaron

**Comment by coreyvickery** [comment]
> can we merge this, start the process of adding it to other component pages, and iterate on the design?

@bennypowers We are discussing the design with Mark today, we should have direction about next steps very soon.

**Comment by bennypowers** [comment]
If it's going to be awhile maybe we should hide the thing, or remove the shortcode from the footer page but merge the infrastructure.

Noting this before I forget: it would be good to show the snippet only first, with a button to load the demo playground. This is how I did it on apolloelements.dev

**Comment by coreyvickery** [comment]
@markcaron @marionnegp I did a quick pass at a design for these demos. If you read above, Benny wants to:

> show the snippet only first, with a button to load the demo playground

I like this approach as it saves a lot of vertical space. We can also use several web components to build this larger one.

https://xd.adobe.com/view/0779bcd8-06d0-49d7-86c3-de81534d70b1-522a/

cc @bennypowers

**Comment by bennypowers** [comment]
@coreyvickery can we do that in a subsequent PR?

**Review by coreyvickery — APPROVED** [review]

**Pull request merged**
