### PR TITLE
chore: update to @patternfly/elements rc

### PR DESCRIPTION
**Pull request by bennypowers**
## What I did

1. install `@patternfly/elements`
2. replace instances of pfe imports and elements
3. upgrade to pfe-tools 1.0 rc
3. upgrade to 11ty 2.0 beta
4. refactor 11ty config
5. nice up the `importMap.cjs` generator for 11ty :crossed_fingers: hopefully this is the one.
6. migrate from npm-run-all to wireit
3. upgrade dependencies

## Testing Instructions

1. check changed docs and dev server demos
2. `git clean -dfx && npm ci && npm start` should run both the wds dev server and the 11ty dev server successfully. warning: this git clean is a destructive operation

Check all these DP demos:

1. [Accordion main demo](https://deploy-preview-725--red-hat-design-system.netlify.app/components/accordion/demo/)
1. [Accordion context nested demo](https://deploy-preview-725--red-hat-design-system.netlify.app/components/accordion/demo/color-context/)
1. [Context Provider main demo](https://deploy-preview-725--red-hat-design-system.netlify.app/components/context-provider/demo/)
1. [Context Provider context nested demo](https://deploy-preview-725--red-hat-design-system.netlify.app/components/context-provider/demo/nested-contexts/)
1. [Footer main demo](https://deploy-preview-725--red-hat-design-system.netlify.app/components/footer/demo/) (social icons)
1. [Global footer nested demo](https://deploy-preview-725--red-hat-design-system.netlify.app/components/footer/demo/global-footer/) (light dom css)
1. [playgrounds](https://deploy-preview-725--red-hat-design-system.netlify.app/components/footer/#demo) (switching playground tabs)
1. [Call to Action demo](https://deploy-preview-725--red-hat-design-system.netlify.app/components/call-to-action/demo/)
1. [Dialog demo](https://deploy-preview-725--red-hat-design-system.netlify.app/components/dialog/demo/)
1. [Stat demo](https://deploy-preview-725--red-hat-design-system.netlify.app/components/statistic/demo/)
1. [Tooltip demo](https://deploy-preview-725--red-hat-design-system.netlify.app/components/tooltip/demo/)

## Notes to Reviewers
- [x] Blocked by https://github.com/patternfly/patternfly-elements/pull/2342
- [x] Blocked by https://github.com/patternfly/patternfly-elements/pull/2358
- [x] Blocked by https://github.com/patternfly/patternfly-elements/pull/2360
- [x] Blocked by https://github.com/patternfly/patternfly-elements/pull/2362
- [x] Blocked by https://github.com/patternfly/patternfly-elements/pull/2367
- even if CI is green, check the test log to make sure all tests indeed ran and passed

### CODE REVIEW

**Comment by bennypowers** [comment]
this is probably blocked on jspm rebuilding our package. i already reached out.

**Comment by bennypowers** [comment]
this should perhaps wait on https://github.com/patternfly/patternfly-elements/pull/2343 to avoid churn

**Comment by zeroedin** [comment]
Should we bump to node 18 to match PFE with this?

**Comment by bennypowers** [comment]
> Should we bump to node 18 to match PFE with this?

indubitably

**Comment by brianferry** [comment]
`Error in your Eleventy config file 'eleventy.config.cjs'. (via EleventyConfigError)
[11ty] 2. Package subpath './11ty/plugins/anchors.cjs' is not defined by "exports"`

**Review by zeroedin — COMMENTED** [review]
Get an error running `npm start`

```
git pull 
git clean -fdx
nvm use
npm ci
npm run start
```
Results in:
```
⬆️ [start] Service started
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './dev-server.js' is not defined by "exports" in /Users/sps/Sites/_rhds/red-hat-design-system/node_modules/@patternfly/pfe-tools/package.json imported from /Users/sps/Sites/_rhds/red-hat-design-system/web-dev-server.config.js
    at new NodeError (node:internal/errors:393:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:358:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:668:3)
    at packageResolve (node:internal/modules/esm/resolve:843:14)
    at moduleResolve (node:internal/modules/esm/resolve:909:20)
    at defaultResolve (node:internal/modules/esm/resolve:1124:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:841:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
❌ [start] Service exited unexpectedly
⬇️ [watch:docs] Service stopped
⬇️ [watch:compile] Service stopped
```

**Comment by bennypowers** [comment]
yeah i got those too
i thought they were fixed, but i'll take another look in the morning

**Comment by zeroedin** [comment]
> yeah i got those too i thought they were fixed, but i'll take another look in the morning

Sounds good, was going down the rabbit, hole, might be some missing exports in `package.json` in `pfe-tools`.

After adding: `import { pfeDevServerConfig } from '@patternfly/pfe-tools/dev-server/config.js';` to `web-dev-server.config.js` `npm start` then fails on`./11ty/plugins/anchors.cjs` not being exported.

**Comment by bennypowers** [comment]
This remains blocked by https://github.com/patternfly/patternfly-elements/pull/2342

**Comment by bennypowers** [comment]
blocked by https://github.com/patternfly/patternfly-elements/pull/2358

**Comment by bennypowers** [comment]
fingers crossed for the "it finally just works" importMaps.cjs solution.

**Comment by bennypowers** [comment]
@heyMP Tests are green in CI, and looks like it's legit, but they were failing for me locally :shrug:

**Comment by bennypowers** [comment]
Missing demos resolved by https://github.com/patternfly/patternfly-elements/pull/2360

**Comment by bennypowers** [comment]
Great catch, @heyMP

**Comment by zeroedin** [comment]
@bennypowers Oh good jspm decided to build tools rc.5 was waiting for it after merge on pfe.  Took awhile and the api build request was throwing an error.

**Comment by bennypowers** [comment]
Blocked on https://github.com/patternfly/patternfly-elements/pull/2362

**Comment by brianferry** [comment]
Noticing a few things in the dev server / running locally

image
Looks like maybe we need to go in and create these screenshots for the main page?

image

Dialog seems to be not getting the styles in the dev server & the demo https://deploy-preview-725--red-hat-design-system.netlify.app/components/dialog/demo/

**Comment by bennypowers** [comment]
> Noticing a few things in the dev server / running locally
> 
> (demo index page): Looks like maybe we need to go in and create these screenshots for the main page?

Yes but that needn't block merge


> Dialog seems to be not getting the styles in the dev server & the demo https://deploy-preview-725--red-hat-design-system.netlify.app/components/dialog/demo/

will take a look, there's an issue with path resolution here

**Comment by bennypowers** [comment]
@brianferry please take another look at the demos and let's get this merged!

**Comment by brianferry** [comment]
Looking at this now, it's looking good! Just a few things noting down here that can be fast follows if we'd like, such as:

1. [Call to Action demo appears to be having an issue importing `pf-panel.js`](https://deploy-preview-725--red-hat-design-system.netlify.app/components/call-to-action/demo/)
2. [Looks like the same thing is happening on dialog as well](https://deploy-preview-725--red-hat-design-system.netlify.app/components/dialog/demo/)
3.[ Footer social icons aren't loading, looks like an issue with trying to load the icons over jspm](https://deploy-preview-725--red-hat-design-system.netlify.app/components/footer/demo/)
4. [Stat appears to be having issues with icons and the @lrnwebcomponents/code-sample resolution](https://deploy-preview-725--red-hat-design-system.netlify.app/components/statistic/demo/)
5. [Tooltip also having the name resolution issue](https://deploy-preview-725--red-hat-design-system.netlify.app/components/tooltip/demo/)

Worth noting too that I am not seeing these issues when running the local dev environment.  Though I am seeing the same button issue locally with dialog

**Comment by brianferry** [comment]
Wait, it looks like the dialog dev server issue might just be that those buttons need updated to be `<pf-button>open</pf-button>` instead of `<pf-button><button>open</button></pf-button>` nvm, not an issue with this PR

**Comment by bennypowers** [comment]
we can follow up trying to trace the demo scripts for install files, but for now we'll do it manually.

Hopefully https://github.com/patternfly/patternfly-elements/pull/2367 will solve the icons issues

**Comment by brianferry** [comment]
@bennypowers

Took a look at the latest on the branch and this is looking great!  I agree that the importMap and some of the regex / object.assign magic is a little much but can be improved on later.

I did notice a few smaller things that can be fast follows,

1. Tabs component looks like it’s trying to pull pf-tab / pf-tabs in but it doesn’t currently get imported.
2. The `call-to-action` analytics page does not load the styles for the code block when in the dev server, but demo page loads correctly.
3. Little add stylings here and there, like the accordion demo always needing to be the full height of the page. 

PR looks good to me 👍

**Comment by bennypowers** [comment]
>     1. Tabs component looks like it’s trying to pull pf-tab / pf-tabs in but it doesn’t currently get imported.
Fixed 
>     2. The `call-to-action` analytics page does not load the styles for the code block when in the dev server, but demo page loads correctly.
Fixed
>     3. Little add stylings here and there, like the accordion demo always needing to be the full height of the page.
???

> PR looks good to me +1
Please drop an approval when you can

**Comment by bennypowers** [comment]
I believe [4407ef9](https://github.com/RedHat-UX/red-hat-design-system/pull/725/commits/4407ef953b67eaf331dcb282c5637c324e24c772) solves the problem of wireit running the 11ty build when tsc artifacts are missing

**Review by brianferry — APPROVED** [review]
Update looks good, thank you for all the work you've done on this @bennypowers!

**Pull request merged**
