### PR TITLE
chore: use pfe.config.json

### PR DESCRIPTION
**Pull request by bennypowers**
## What I did

1. use .pfe.config.json

Depends on https://github.com/patternfly/patternfly-elements/pull/2112

### CODE REVIEW

**Comment by zeroedin** [comment]
Maybe getting ahead of myself or missing something crucial, but attempted to test this by copying `@patternfly/pfe-tools` from a built https://github.com/patternfly/patternfly-elements/pull/2112 

Am now getting file path issues with the demo/demo.css the demo/component.js had to rewrite those paths in the demo file seemed to work but not ideal.

```
http://localhost:8000/elements/rh-call-to-action/demo/demo.css | 404 | stylesheet | demo.css | 202 B | 30 ms
http://localhost:8000/elements/rh-call-to-action/demo/rh-cta.js | 404 | script | rh-cta.js
```

```
<link rel="stylesheet" href="../../cta/demo/demo.css" />
<script type="module" src="../../cta/demo/rh-cta.js"></script>
```

Will double-check this when https://github.com/patternfly/patternfly-elements/pull/2112  is merged.

**Comment by bennypowers** [comment]
> Maybe getting ahead of myself or missing something crucial, but attempted to test this by copying `@patternfly/pfe-tools` from a built [patternfly/patternfly-elements#2112](https://github.com/patternfly/patternfly-elements/pull/2112)
> 
> Am now getting file path issues with the demo/demo.css the demo/component.js had to rewrite those paths in the demo file seemed to work but not ideal.
> 
> ```
> http://localhost:8000/elements/rh-call-to-action/demo/demo.css | 404 | stylesheet | demo.css | 202 B | 30 ms
> http://localhost:8000/elements/rh-call-to-action/demo/rh-cta.js | 404 | script | rh-cta.js
> ```
> 
> ```
> <link rel="stylesheet" href="../../cta/demo/demo.css" />
> <script type="module" src="../../cta/demo/rh-cta.js"></script>
> ```
> 
> Will double-check this when [patternfly/patternfly-elements#2112](https://github.com/patternfly/patternfly-elements/pull/2112) is merged.

yeah we'll need to fix this in https://github.com/patternfly/patternfly-elements/pull/2112

we need the dev server to deslugify aliases

**Comment by bennypowers** [comment]
@zeroedin @brianferry this is now ready for review

**Comment by bennypowers** [comment]
https://deploy-preview-495--red-hat-design-system.netlify.app/components/call-to-action/demo/ :/

somethings not right here
will have to take another look at it next week

**Comment by bennypowers** [comment]
ok deploy preview is fixed

**Comment by bennypowers** [comment]
ok for keepsies this time https://deploy-preview-495--red-hat-design-system.netlify.app/components/call-to-action/demo/

**Review by zeroedin — APPROVED** [review]

**Pull request merged**
