### PR TITLE
fix(table): improve color contrast of hover state

### PR DESCRIPTION
**Pull request by marionnegp**
## What I did

1.

## Testing Instructions

1.

### CODE REVIEW

**Comment by marionnegp** [comment]
I was trying to edit the row hover color for dark theme, and the lightDOM CSS keeps overriding the `.dark` CSS. What's the best way to fix this?

Dark theme hover colors were working in when they were first added in (#1373), but maybe some of the color palette/theming updates changed it.

**Comment by bennypowers** [comment]
i pushed some commits which juggle the css syntax, but the values appear to be the same as on clefairy: blue-50 at 10% for columns, gray-20 at 40% for rows.

**Comment by bennypowers** [comment]
I added a link in the color contrast demo, for testing this issue
I also sneakily added an unrelated fix for a certain context hack which shall not be mentioned

**Comment by bennypowers** [comment]
compare clefairy base line: https://deploy-preview-1802--red-hat-design-system.netlify.app/elements/table/demo/color-context/
to this pr: https://deploy-preview-1896--red-hat-design-system.netlify.app/elements/table/demo/color-context/

**Comment by marionnegp** [comment]
Thanks, @bennypowers! I thought this was going to be a quicker CSS fix. 😅

**Comment by coreyvickery** [comment]
@marionnegp The hover state in `Light` is getting a bit lost.

**Comment by marionnegp** [comment]
@coreyvickery, can you take another look? I replaced the hover color with a darker gray at a lower opacity, so it shows up on all our light theme surfaces.

**Review by coreyvickery — APPROVED** [review]

**Pull request merged**
