### PR TITLE
docs: section spacing

### PR DESCRIPTION
**Pull request by nikkimk**
## What I did

1. Removed section shortcodes and cleaned up extra spacing from docs pages.
2. Added `margin-top: 80px` before h2 elements in `_base.scss`
3. Removed margins from empty paragraph elements in `_base.scss`

## Testing Instructions

1. Review docs pages in [DP](https://deploy-preview-1055--red-hat-design-system.netlify.app/).
2. Make sure spacing above h2 elements is 80px.
3. Make sure that find & replace did not break any page.

### CODE REVIEW

**Comment by bennypowers** [comment]
I added a commit which loads font from the repository instead of from static.redhat.com. This is to avoid cors problems:

> downloadable font: download failed (font-family: "RedHatDisplay" style:normal weight:400 stretch:100 src index:1): bad URI or cross-site access not allowed source: https://static.redhat.com/libs/redhat/redhat-font/2/webfonts/RedHatDisplay/RedHatDisplay-Medium.woff 

I also added a commit which uses the logo svg for favicon, also sourced locally.

**Comment by bennypowers** [comment]
I scoped the header margins to element docs pages only. further PRs can spread that to other page types

**Review by bennypowers — APPROVED** [review]
Calling it! we can mop up later if we find discrepancies

Nice work

**Comment by coreyvickery** [comment]
@nikkimk Not sure why this was merged.

Example of spacing not meeting the XD specs (Accordion page from the DP link):

Screen Shot 2023-06-12 at 1 02 30 PM
Screen Shot 2023-06-12 at 1 02 39 PM

**Comment by bennypowers** [comment]
@coreyvickery thanks for the review. see https://github.com/RedHat-UX/red-hat-design-system/pull/1062

**Comment by coreyvickery** [comment]
@nikkimk Disregard when you see this.

**Pull request merged**
