### PR TITLE
docs: create minimal theme sheet for demos

### PR DESCRIPTION
**Pull request by bennypowers**
## What I did

1. [x] add a minimal theme (base.css)
2. [x] add a demo stylesheet (demos.css)
3. [x] transform demos in 11ty so they load lightdom css from the correct path

## Testing Instructions

1. run dev server and 11ty build, and check deploy preview at https://deploy-preview-447--red-hat-design-system.netlify.app/components/footer/demo/global-footer/

### CODE REVIEW

**Comment by heyMP** [comment]
Nice stuff @bennypowers.  I can't tell if it's loading the correct base styles.  Can you verify?
Screen Shot 2022-07-30 at 9 59 34 AM

Screen Shot 2022-07-30 at 10 02 05 AM

**Comment by bennypowers** [comment]
This is blocked on https://github.com/patternfly/patternfly-elements/issues/2079 which is preventing releases in pfe

**Comment by bennypowers** [comment]
@heyMP ok this should be g2g now

**Comment by heyMP** [comment]
Sorry, jumped the gun.  Reviewing now! 👍

**Review by heyMP — APPROVED** [review]
Lift Goats That Matter 🐐

**Pull request merged**
