### PR TITLE
feat(card): heading typography

### PR DESCRIPTION
**Pull request by bennypowers**
## What I did

1. add new css props for heading typography
2. update the variants.html demo (likely to conflict with promo pr)

## Testing Instructions

1. compare all [demos](deploy-preview-1701--red-hat-design-system.netlify.app/elements/card/demos/) to main branch
2. https://deploy-preview-1701--red-hat-design-system.netlify.app/elements/card/demo/
3. https://deploy-preview-1701--red-hat-design-system.netlify.app/elements/card/demo/color-context/

## Notes to Reviewers

Some users may consider this breaking, as it adds `!important` to heading css.
cc @OneEightyFirst @zhawkins. Note that this is scheduled for Charmander (2.0)

### CODE REVIEW

**Review by marionnegp — CHANGES_REQUESTED** [review]
The demos on the [Demos subpage](https://deploy-preview-1701--red-hat-design-system.netlify.app/elements/card/demos/) aren't showing the right heading styles, but they look more correct in the fullscreen demo. Not sure why.

Some edits based on the fullscreen demo view:
- [x] When a title/heading is in the bar, font family should be `--rh-font-family-body-text` and font weight should use `--rh-font-weight-body-text-regular`
- [ ] Heading's line height should be `--rh-line-height-heading`

**Review by marionnegp — CHANGES_REQUESTED** [review]
I checked off the heading styles when it's in a title bar. Thanks!

The line height for headings in the header still needs to be `var(--rh-line-height-heading, 1.3)`. Seeing computed values using 1.5.
Screenshot 2024-07-12 at 3 07 14 PM

**Comment by bennypowers** [comment]
@marionnegp PTAL. I observed that - maddeningly - the computed value in dev tools was 1.5, however, it actually displayed with 1.3.

I confirmed that by inspecting the heading element and running this in the console:

```js
getComputedStyle($0).lineHeight
"31.2px" 
```

**Comment by bennypowers** [comment]
@marionnegp I'm going to merge this into the `staging/charmander` branch. If line height remains problematic, let's open a new issue. TY!

**Comment by marionnegp** [comment]
> @marionnegp I'm going to merge this into the `staging/charmander` branch. If line height remains problematic, let's open a new issue. TY!

Looks like it's working now. Thanks!

**Pull request merged**
