### PR TITLE
docs: images not rendering on patterns landing page

### LINKED ISSUE #1070: [docs]: images under https://ux.redhat.com/patterns/ not rendering

### PR DESCRIPTION
**Pull request by eyevana**
Closes #1070

## What I did

1. Added `srcAbsolute` to the example images shortcode to correct the image paths under /patterns
2. Updated images and summaries

## Testing Instructions

1. You should see images again in the [DP](https://deploy-preview-1071--red-hat-design-system.netlify.app/patterns/)
2. & they should match the [design spec](https://xd.adobe.com/view/0f123ffb-ae98-411e-ada3-2526129e0c74-5a41/)

### CODE REVIEW

**Comment by brianferry** [comment]
Looks good to me, if we have the card image we should add that but otherwise looks g2g

**Comment by coreyvickery** [comment]
@eyevana Ready for you.

XD: https://xd.adobe.com/view/0f123ffb-ae98-411e-ada3-2526129e0c74-5a41/
Content doc: https://docs.google.com/document/d/1DIwKX9S707VmH2SnmZyqBLCpHb7ozZkzu0cWlLpzbZU/edit
Images: https://www.dropbox.com/sh/94lqqs0xhtusji9/AABHvx_WvuKM8JbUdmV8gu7ya?dl=0

**Comment by eyevana** [comment]
@coreyvickery with the exception of that comment I made in the content doc, this is ready for your review :)

**Review by coreyvickery — APPROVED** [review]
@eyevana Looks good!

**Pull request merged**
