### PR TITLE
docs(secondary-nav): add docs page

### PR DESCRIPTION
**Pull request by coreyvickery**
## What I did

1. Created a new page for the `Secondary navigation` component

### CODE REVIEW

**Comment by marionnegp** [comment]
- [ ] Can the primary navigation link in the sidebar be changed to "Navigation (primary)"? You had that in a mockup.

- [ ] Under Style > Theme options, I think a comma can be added before "unless" in theses: `The drop shadow is always visible when scrolling or not unless covered by an expandable tray.` and `The thin gray line is always visible when scrolling or not unless covered by an expandable tray.` The wording of the second half was a little confusing.

- [ ] Under Usage > Secondary navigation, did you mean to include the helpful tip? It's in a previous section.

- [ ] Under Usage > Writing navigation content, change "less" to "fewer" in `* If there are fewer menus and links in Zone 2, more characters can be written; if there are more menus and links, less characters can be written`. It's a picky note, but I figured it should be consistent since you used "fewer" in the same sentence.

- [ ] For the images that have notes in fuschia, do you want to change those to blue now, or do you want to make that change in the bigger site redesign?  We can always pick a different color for notes in the redesign too.

- [ ] Under Behavior > Collapsing the expandable tray, should `Clicking or tapping anywhere outside of the expandable tray should collapse it.` say `Clicking or tapping anywhere outside of the secondary navigation...` instead? I tried clicking on an empty space in the secondary nav, and it didn't close the tray.

- [ ] Under Interaction states > Focus, it looks like the text in Zone 1 is a different color from the links in Zone 2, but the table says they should be the same?

- [ ] Under Accessibility > Keyboard events, I think the table headings should change to "Action" and "Event." Also, are the last two rows supposed to say `Active (all themes)`?

- Not an edit: I like how you explained the expandable tray scrolling. Not a super easy thing to convey.

**Review by marionnegp — COMMENTED** [review]
- [x] Under Style > Theme options, I think a comma can be added before "unless" in theses: `The drop shadow is always visible when scrolling or not unless covered by an expandable tray.` and `The thin gray line is always visible when scrolling or not unless covered by an expandable tray.` The wording of the second half was a little confusing.

- [x] Under Usage > Secondary navigation, did you mean to include the helpful tip? It's in a previous section.

- [x] Under Usage > Writing navigation content, change "less" to "fewer" in `* If there are fewer menus and links in Zone 2, more characters can be written; if there are more menus and links, less characters can be written`. It's a picky note, but I figured it should be consistent since you used "fewer" in the same sentence.

- [x] For the images that have notes in fuschia, do you want to change those to blue now, or do you want to make that change in the bigger site redesign?  We can always pick a different color for notes in the redesign too.

- [ ] Under Behavior > Collapsing the expandable tray, should `Clicking or tapping anywhere outside of the expandable tray should collapse it.` say `Clicking or tapping anywhere outside of the secondary navigation...` instead? I tried clicking on an empty space in the secondary nav, and it didn't close the tray.

- [ ] Under Interaction states > Focus, it looks like the text in Zone 1 is a different color from the links in Zone 2, but the table says they should be the same?

- [ ] Under Accessibility > Keyboard events, I think the table headings should change to "Action" and "Event." Also, are the last two rows supposed to say `Active (all themes)`?

- Not an edit: I like how you explained the expandable tray scrolling. Not a super easy thing to convey.

**Review by ronniemcbride — COMMENTED** [review]
Section: Anatomy

- [x]  I think the first zone 123 image should go above the bulleted list. And the helpful hints should stay where it is. 



Section: Zones on small breakpoints

- [x]  Do you think the small breakdown image should contain the accordion arrow carat image representing what you said in the copy?

**Review by ronniemcbride — APPROVED** [review]

**Comment by bennypowers** [comment]
Please squash when merging, thanks

**Pull request merged**
