### PR TITLE
docs(tooltip): updated tooltip docs based on feedback in #972

### PR DESCRIPTION
**Pull request by nikkimk**
## What I did

1. Updated tooltip docs #922 .

## Testing Instructions

1. Review the [feedback](https://github.com/RedHat-UX/red-hat-design-system/pull/972#issuecomment-1569047399) given in #972.
2. View [DP tooltip docs](https://deploy-preview-1021--red-hat-design-system.netlify.app/elements/tooltip/).
3. Compare to [tooltip doc](https://docs.google.com/document/d/1HUa31FFVjv0Sl1qSt0qABqLyBsJ5hcL8ByxlT5Bg2Ko/edit#) and to [Docs cleanup checklist](https://github.com/RedHat-UX/red-hat-design-system/wiki/Docs-Cleanup-Q2-2023-Checklist).

## Notes to Reviewers
Ignore the following as they will be resolved in future issues:
- #1026 
- #1024

### CODE REVIEW

**Comment by coreyvickery** [comment]
@nikkimk Final edits:

### Global
- Change the line height of bullets to `2` across the website

### Style tab
- Under the `Dark theme` h3, the container is not 100% black (#151515)
- Under the `Space` h2, the spacer images are broken, I am assuming because we are transitioning to Steven's solution (also, make sure that px and rem values are on two lines)

### Guidelines
- Change the `Tooltip vs. popover` text to h3
- Under the `Responsive design` h2, the image looks a little bit blurry; the image is technically 992px wide and I suspect it is being stretched to 1000px again

**Comment by nikkimk** [comment]
> * Change the line height of bullets to `2` across the website

That will be addressed in #1026

**Comment by nikkimk** [comment]
> Under the Responsive design h2, the image looks a little bit blurry; the image is technically 992px wide and I suspect it is being stretched to 1000px again

@coreyvickery that will be fixed in #1024

**Comment by nikkimk** [comment]
@coreyvickery PTAL, as I think I got everything other than the stuff that will update automatically when the other PRs are merged.

**Review by coreyvickery — APPROVED** [review]
Looks good.

**Pull request merged**
