### PR TITLE
Removed openshift.com from home page content

### PR DESCRIPTION
**Pull request by ryanaltvater**
supercedes #231

### CODE REVIEW

**Comment by bennypowers** [comment]
Thanks! looks like there's a conflict, specifically, that the changes in `pages/_templates/layout-base.njk` should be in `docs/_includes/layout-base.njk`, and likewise for `pages/index.njk` should be in `docs/index.njk`

**Comment by ryanaltvater** [comment]
@bennypowers Ah, okay. `main` is the default branch, and so I created a branch off of that. So I didn't have a `docs` folder when I made the changes. I'll shift things over to use the `design-system` branch, and then make the changes in the correct spot.

Maybe switch `design-system` in the settings as the "default" branch for people to start from? 🤷‍♂️

**Comment by bennypowers** [comment]
we're planning on merging that branch shortly, which is why I asked you to rebase off that one.

apologies for the confusion

**Comment by ryanaltvater** [comment]
Okay cool, noted! 😄

**Pull request closed without merging**
