### PR TITLE
docs(avatar): update docs

### PR DESCRIPTION
**Pull request by diwanshi**
## What I did

1. Updated the docs for rh-avatar element based on the specs mentioned in https://github.com/RedHat-UX/red-hat-design-system/issues/909 

## Testing Instructions

1. Review the updated docs for [rh-avatar(preview)](https://deploy-preview-1002--red-hat-design-system.netlify.app/elements/avatar/) and check if they match the [design spec](https://xd.adobe.com/view/6f3078cf-c5d5-4c7b-8e30-509acd11525c-3a63/) and the [content](https://docs.google.com/document/d/1eEnyWKABadmP4RetzXIB7HXX542C9n-Dj_jjQ4uE_XI/edit?usp=sharing)

### CODE REVIEW

**Comment by coreyvickery** [comment]
@diwanshi Looks fantastic! Some tiny edits:

### Style tab
- Spacer image in table is still 2x
- Change `Interaction States` heading to `Interaction states`

### Guidelines tab
- `Small breakpoints` heading, image still looks 2x
- Change `Best Practices` heading to `Best practices`

**Comment by bennypowers** [comment]
see #1005 and #949 wrt spacer images

**Comment by coreyvickery** [comment]
@diwanshi Final edits:

### Overview page
- Add a check in the `RHDS` column

### Guidelines page
- Under the `Best practices` h2 and `Thumbnail shape` h3, I updated the image and the new version is on Dropbox

**Comment by diwanshi** [comment]
@coreyvickery ready for the review.

**Review by coreyvickery — APPROVED** [review]
Looks great.

**Review by bennypowers — APPROVED** [review]
Nice work, @diwanshi :)

**Comment by bennypowers** [comment]
i'll take a look

**Pull request merged**
