### PR TITLE
docs(subnav): add docs content

### LINKED ISSUE #932: [docs] Subnav docs need review/cleanup
Please review sections and ensure docs are complete.

Current tabs: Overview, Code. No content in the Overview tab, currently. Code section is pretty lean, too. No Guidelines tab.

Previous IA Docs update issue: none

Tag @coreyvickery for final design review.

### PR DESCRIPTION
**Pull request by bennypowers**
Closes #932

## What I did

1. Add subnav docs per [XD](https://xd.adobe.com/view/258ee636-1778-4e80-9ee3-17a5568e3ef1-70dd/screen/8f79bbec-505b-4040-b465-29e035d147ab/specs/)

TBD:
- [x] alt text (see comments)
- [x] token tables (see https://github.com/orgs/RedHat-UX/discussions/1059)

### CODE REVIEW

**Comment by bennypowers** [comment]
@nikkimk the graphics here are pngs, and some of them contain text-as-image. I suspect that if we loaded svgs (via img tag) we would not need alt text if we embedded it in the `<title>` tag of the svg, as well the inline text would be announced. is that correct?

**Comment by nikkimk** [comment]
> @nikkimk the graphics here are pngs, and some of them contain text-as-image. I suspect that if we loaded svgs (via img tag) we would not need alt text if we embedded it in the `<title>` tag of the svg, as well the inline text would be announced. is that correct?

@bennypowers If the SVG code is actually on the page, you'd be correct. But if you're doing an `` you would still need alt text. Screen readers can only read SVG markup if it's actually on the page as markup.

**Comment by bennypowers** [comment]
Thanks @nikkimk in any case, I copied the alt text from Corey's doc

**Comment by bennypowers** [comment]
@coreyvickery this is ready for review. if it meets your standards, please formally approve, otherwise, please formally request changes in the `files changed` tab. tyvm

**Comment by coreyvickery** [comment]
@bennypowers Edits.

### Overview page
- [ ] Under the `Overview` h2, the image in the container is missing

### Style page
- [ ] Under the `Space` h2, the alert is not displaying the new style updates
- [ ] Under the `Interaction states` h2, under the `Focus` and `Active` h3s, the alert is not displaying the new style updates

### Guidelines page
- [ ] Under the `Usage` h2, `Number of links` and `Inset` should be h3s
- [ ] Under the `Writing content` h2, `Link text labels` should be an h3
- [ ] Under the `Layout` h2, the image should not be in a container
- [ ] Under the `Behavior` h2, `Scrolling` should be an h3
- [ ] Under the `Behavior` h2, under the `With primary navigation` and `With heading` h3s, the images should not be in containers
- [ ] Under the `Behavior` h2, `Navigating overflow links` should be an h3
- [ ] Under the `Responsive design` h2, under the `Large breakpoints` h3, the image should not be in a container
- [ ] Under the `Responsive design` h2, change the `Small` h3 to `Small breakpoints`
- [ ] Under the `Responsive design` h2, under the `Small breakpoints` h3, the image should not be in a container

### Accessibility page
- [ ] Under the `Keyboard interactions` h2, the alert is not displaying the new style updates

**Review by coreyvickery — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
