### PR TITLE
docs: make subnav sticky

### LINKED ISSUE #1060: [docs]: subnav should be sticky
[subnav docs](https://xd.adobe.com/view/258ee636-1778-4e80-9ee3-17a5568e3ef1-70dd/screen/1a3cd010-d9e5-4801-8a08-7d8e741c4375/specs/) (thanks @coreyvickery for putting these together) say that subnav should be sticky

### PR DESCRIPTION
**Pull request by bennypowers**
Closes #1060

## What I did

1. make the subnav's container sticky, calculating the height of the whitespace and header

## Testing Instructions

1. check out an elements page in the dp

### CODE REVIEW

**Comment by brianferry** [comment]
Looks good on screens < 1400px, though I think we might need a different stylesheet for >= 1400px

image

Looks like when the screen is >= 1400px, the .header class gets a padding left, top, and right.  Also the padding on the h1 element changes because the font-size changes to 48px.

**Comment by bennypowers** [comment]
Thanks @brianferry. PTAL. should fix large screens. mobile still has some issues, but I think we can merge anyways and go back after this release to fix the styles in a more fundamental way (i.e. use tokens)

that being said if you wanna tinker, go right ahead, just commit here and merge when it looks good to you

**Comment by zeroedin** [comment]
> should fix large screens

Nice work, this looks great!

**Comment by coreyvickery** [comment]
@bennypowers Looks good to me.

**Pull request merged**
