### PR TITLE
docs(devs): adding lightdom shim css explanation and cross-linking

### PR DESCRIPTION
**Pull request by markcaron**
## What I did

1. Updated / added / improved the Devs Get Started explanation on "Lightdom CSS" and "Lightdom CSS shims" to help with confusion.
2. Cross-linked the `renderLightDom.cjs` shortcode to the explainer.

## Testing Instructions

1. Proofread and check accuracy

### CODE REVIEW

**Comment by bennypowers** [comment]
can we merge #1941 first then update this?

**Comment by markcaron** [comment]
> can we merge #1941 first then update this?

@bennypowers, sure.

**Review by bennypowers — APPROVED** [review]

**Comment by bennypowers** [comment]
@markcaron PTAL and merge when you're ready

**Review by bennypowers — APPROVED** [review]
Lightdom gives them measles

**Pull request merged**
