### PR TITLE
docs: fix headers and add screenshots

### LINKED ISSUE #890: [bug] Broken images and missing headings on All Elements and All Patterns pages
### Describe the bug

- [ ] Fix broken images on [All Elements page](https://ux.redhat.com/elements/) and [All Patterns page](https://ux.redhat.com/patterns/)
- [ ] Add headings below each image on both pages

### Which Component?

n/a

### Steps to reproduce

See [All Elements page](https://ux.redhat.com/elements/) and [All Patterns page](https://ux.redhat.com/patterns/)

### Expected behaviour

Should be showing images and headings

### Screenshots

_No response_

### Element HTML

_No response_

### Operating System (OS)

macOS

### Browser

_No response_

### More browser information

_No response_

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by zeroedin**
## What I did

1. Fixed headers for `/elements/` and `/patterns/` and wrapped them with a link

Closes #890 

**Todo:**

Add screenshots for elements:
- [x] Badge
- [x] Blockquote
- [x] Button
- [x] Footer
- [x] Navigation Primary
- [x] Navigation Secondary
- [x] Pagination
- [x] Spinner
- [x] Stat
- [x] Subnav
- [x] Tag

Add screenshots for patterns:
- [x] Link
- [x] Promo
- [x] Search bar
- [x] Skip Navigation
- [x] Sticky Banner
- [x] Sticky Card
- [x] Video thumbnail

## Testing Instructions

1. View [deploy preview docs](https://deploy-preview-891--red-hat-design-system.netlify.app)

### CODE REVIEW

**Comment by marionnegp** [comment]
**Pattern screenshots**
- [ ] Most of the patterns just need a different file name/file type. Here are the correct ones in the docs/assets folder:

  - /assets/patterns/link-with-icon.svg
  - /assets/patterns/promo.svg
  - /assets/patterns/search-bar.svg
  - /assets/patterns/skip-nav.svg
  - /assets/patterns/sticky-banner.svg
  - /assets/patterns/sticky-card.svg
  - /assets/patterns/video-thumbnail.svg

- [ ] I updated the thumbnail for `rh-announcement` because the current one looks like the announcement is supposed to be below the primary nav, which isn't correct.
announcement

- [ ] The boxes for the `rh-announcement` and `rh- promo` need an extra CSS class to add a background color. You won't be able to see promo.svg until the blue one is added. Announcement's bg color should be `var(--rh-color-surface-lighter, #f2f2f2)` now.
Screenshot 2023-04-04 at 11 47 01 AM
Screenshot 2023-04-04 at 11 44 27 AM

**Comment by marionnegp** [comment]
**Component screenshots:**

- [ ] The following exist but need a different file name/type: 

  - /elements/blockquote/screenshot.png
  - /elements/button/button.svg
  - /elements/footer/screenshot.png
  - /elements/navigation-primary/screenshot.png
  - /elements/navigation-secondary/screenshot.png

- [ ] The following are new:

- pagination:
  pagination
-   spinner:
  spinner
-   statistic:
  statistic
-   subnav (this will need a `--rh-color-surface-lighter` bg, like `rh-announcement`.):
  subnav
-   tag:
  tag

- [ ] `rh-dialog`'s screenshot needs a bg of `--rh-color-gray-90-rgb` with an opacity of `--rh-opacity-60`

**Comment by zeroedin** [comment]
@coreyvickery I requested a review from you, @marionnegp looks like she still had a couple todo items in a comment above left unfinished, let me know if there is anything I can help you with to get this PR over the finish line.

**Comment by bennypowers** [comment]
If there's nothing broken here can we merge it and spin the leftovers into a new issue?

**Comment by coreyvickery** [comment]
@zeroedin Seems like the remaining work is just adding or changing CSS. You should be able to knock that out in minutes.

**Comment by zeroedin** [comment]
> @zeroedin Seems like the remaining work is just adding or changing CSS. You should be able to knock that out in minutes.

You are right should have looked a bit closer, thought maybe there was some missing images still needing to be added.  I'll close those CSS adds out and then ping for a review.

**Comment by zeroedin** [comment]
> * [ ]   `rh-dialog`'s screenshot container needs a bg of `--rh-color-gray-90-rgb` with an opacity of `--rh-opacity-60`
> * [ ]  `rh-subnav`'s screenshot container needs a bg of `--rh-color-surface-lighter` bg, like `rh-announcement`

If i understood these correct.
The dialog screenshot container, needed to have a background representing the overlay to distinguish it from the rest of the container.
image

The screenshot for subnav needed adjusted to have the the background color as shown in the component demos.

image

If these are incorrect assumptions let me know and I can revert these changes.

**Comment by coreyvickery** [comment]
@zeroedin Sounds right to me.

**Review by nikkimk — COMMENTED** [review]
lgtm

**Review by bennypowers — APPROVED** [review]

**Comment by bennypowers** [comment]
If there are any leftovers, please spin them out into new issues

**Pull request merged**
