### PR TITLE
docs: example image css

### PR DESCRIPTION
**Pull request by nikkimk**
## What I did

1. Resolves [#979](https://github.com/RedHat-UX/red-hat-design-system/issues/979). Adjusted default example image size since the example images are 2X the desired size by using: `width: auto; transform: scale(0.5); margin: -7.5% auto;`

## Testing Instructions

1. Check [DP](https://deploy-preview-991--red-hat-design-system.netlify.app/) for issues with image size.

### CODE REVIEW

**Comment by bennypowers** [comment]
can we do this without `transform`?

**Comment by coreyvickery** [comment]
@bennypowers Back when the whole website ran on `.njk` files, for each image, Marionne and I would add widths to a `max-width` property in the `` tag. For example:

`Anatomy of a tooltip`

Doing this always ensured the images were the exact width as designed in our XDs. Is there a way to get back to that point without using the `max-width` property? Am I exporting images from XD incorrectly? We have always exported them at 2x so they render sharply.

**Comment by bennypowers** [comment]
`width` and `height` attrs are preferable because the browser can allocate space early on (especially vertical space with `height`)

As well, automated tools like jampack can use the `width` and `height` attrs to generate optimized image `srcsets` for us at build time

**Comment by nikkimk** [comment]
@bennypowers I took your advice and used Eleventy's responsive image to generate srcsets. ptal.

**Review by bennypowers — APPROVED** [review]

**Pull request merged**
