### PR TITLE
Updating breakpoints table per token conversations

### PR DESCRIPTION
**Pull request by coreyvickery**
## What I did

1. Updating breakpoints table per token conversations.

### CODE REVIEW

**Comment by bennypowers** [comment]
here too, shouldn't this be addressed in the tokens repo?

**Comment by coreyvickery** [comment]
@bennypowers In this case, it is updating the page on ux dot with current design token values.

**Comment by bennypowers** [comment]
shouldn't the ux page get it's values from the tokens repo? why keep two sets of tokens?

**Review by marionnegp — APPROVED** [review]

**Comment by marionnegp** [comment]
@bennypowers @coreyvickery, we'll have to figure out how to make the breakpoint naming on [ux.redhat.com](https://ux.redhat.com/foundations/grid/#breakpoints) match what we have in the [tokens](https://red-hat-design-tokens.netlify.app/#breakpoints). Not sure which page would get the updates.

**Comment by marionnegp** [comment]
@bennypowers @coreyvickery, we'll have to figure out how to make the breakpoint naming on [ux.redhat.com](https://ux.redhat.com/foundations/grid/#breakpoints) match what we have in the [tokens](https://red-hat-design-tokens.netlify.app/#breakpoints). Not sure which page would get the updates.

**Review by marionnegp — APPROVED** [review]

**Pull request merged**
