### PR TITLE
docs: correct header layout

### LINKED ISSUE #1158: [docs] Header padding
### Description

The padding below the h1 on some pages seems to have been reduced or deleted when `rh-subnav` was added.

### Section page
Screen Shot 2023-07-18 at 10 29 37 PM

### Pattern page
Screen Shot 2023-07-18 at 10 28 59 PM

---

On desktop pages without `rh-subnav`, the padding below an h1 should be `--rh-space-5xl` or 80px.

### Acceptance Criteria

- [X] Design done
- [ ] Development done

### Image

_No response_

### Link to design doc

_No response_

### Other resources

_No response_

### PR DESCRIPTION
**Pull request by bennypowers**
Fixes #1158

## What I did

1. add `has-subnav` class to header on pages which... have subnav

## Testing Instructions

1. https://deploy-preview-1165--red-hat-design-system.netlify.app/elements/accordion/
2. https://deploy-preview-1165--red-hat-design-system.netlify.app/patterns/announcement/
3. https://deploy-preview-1165--red-hat-design-system.netlify.app/design-code-status/

## Notes to Reviewers

We can replace that class with `:has(rh-subnav)` later on

### CODE REVIEW

**Comment by coreyvickery** [comment]
@bennypowers I changed `.header .page-title:only-child { margin-bottom: 0; }` to `.header .page-title:only-child { margin-bottom: 3rem; }` and it looks exactly what I had in mind visually. Any issues moving forward with this?

**Review by coreyvickery — CHANGES_REQUESTED** [review]
@bennypowers I changed `.header .page-title:only-child { margin-bottom: 0; }` to `.header .page-title:only-child { margin-bottom: 3rem; }` and it looks exactly what I had in mind visually. Any issues moving forward with this?

**Comment by bennypowers** [comment]
@coreyvickery please clarify: the changes in this PR don't do what you intended?

**Review by coreyvickery — APPROVED** [review]
Perfect.

**Pull request merged**
