### PR TITLE
docs: add edit this page link

### LINKED ISSUE #1441: [docs] Add "Edit this page" on docs pages
It'd be helpful to add an "Edit this page" link at the bottom of our docs pages. This might help attract new contributors to the docs as well.

- [ ] Make it happen

### PR DESCRIPTION
**Pull request by zeroedin**
## What I did

1. Added an edit this page link that links to the github file.

Closes #1441 

## Testing Instructions

1. View the deploy preview.  
2. Note that links target the `main` branch and this PR is based on staging/clefairy.  So some links such as `docs/theming/index.md` which do not exist on branch `main` will be broken.
3. I left the homepage of `ux.` out of having a edit this page link.  If we want to add it let me know.

### CODE REVIEW

**Comment by bennypowers** [comment]
I wasn't able to click the edit this page links, neither on foundations, tokens, nor elements pages, on my OnePlus nord ce2, chrome or Firefox

**Comment by coreyvickery** [comment]
@zeroedin I was redirected when clicking the link using the latest Chrome, but like you said, sometimes it 404s. Styling looks fine to me too.

IMO, we should remove it from the sections below, the rational being we don't want just anyone editing content about the design system as a whole or how people should use it except for the team.

- About
- Get started

**Comment by bennypowers** [comment]
> we don't want just anyone editing content 

Any edits would have to be vetted by PR review, anyways

The only people who can make changes to any content are users with "Write" access to this repo. Everyone else has to make a PR and request a review

**Comment by bennypowers** [comment]
https://deploy-preview-1882--red-hat-design-system.netlify.app/patterns/ no link here

**Comment by coreyvickery** [comment]
Missing on these pages too:

- https://deploy-preview-1882--red-hat-design-system.netlify.app/patterns/card/
- https://deploy-preview-1882--red-hat-design-system.netlify.app/patterns/logo-wall/ (all subpages)
- https://deploy-preview-1882--red-hat-design-system.netlify.app/patterns/tile/

**Review by bennypowers — APPROVED** [review]

**Pull request merged**
