### PR TITLE
docs: tokens

### LINKED ISSUE #719: [docs]: Add Tokens pages
Implement docs pages for tokens, using the new 11ty plugin

https://xd.adobe.com/view/54aea3e4-4896-4823-9833-e40f1195e7c6-01fd/grid

One approach to implementing search:
https://claytonerrington.com/blog/adding-a-basic-search/
or maybe https://pagefind.app/

### LINKED ISSUE #883: [feat] Design token copy button with tooltip for ux.redhat.com
### Description

# Brief

We need to give users the ability to copy a design token name on ux.redhat.com.

# Needs

- The name text should have a light gray background with padding and rounded corners
- There should be a copy to clipboard button
- The copy button should display a tooltip on hover with `Copy to clipboard` text
- The tooltip should be oriented on the top of the button
- The copy button should display `Copied` confirmation text when selected for a duration of `3 seconds` then return to `Copy to clipboard` text ([example](https://polaris.shopify.com/tokens/colors))
- The design token name should then be copied to the clipboard
- `rh-tooltip` can be used

# Styles

### Text

- Font: RH Text Regular
- Size: 14px / 21 (1.5 line height)
- Letter spacing: 0.2px
- Color: #151515

### Icon

- Default color: #6A6E73
- Hover color: #151515

### Background

- Border radius: 3px
- Color: #F5F5F5

### Acceptance Criteria

- [ ] Design done
- [ ] Development done

### Image

_No response_

### Link to design doc

https://xd.adobe.com/view/7dae9ef8-4dd4-4a8a-a05a-6192132c5e9f-28fd/

### Other resources

design-token-copy-button-icon-default
design-token-copy-button-icon-hover

### PR DESCRIPTION
**Pull request by bennypowers**
Closes #719 
Closes #883 

## What I did

1. Added a single-page tokens entry to docs
2. Added tokens pages for single categories

## Testing Instructions

1. [Overview Page](https://deploy-preview-717--red-hat-design-system.netlify.app/tokens/)

## Notes to Reviewers
- [x] Blocked by https://github.com/patternfly/patternfly-elements/pull/2316
- [x] Blocked by #725 
- [x] Blocked by https://github.com/RedHat-UX/red-hat-design-tokens/pull/68
- [x] Blocked by #868

### CODE REVIEW

**Comment by bennypowers** [comment]
could be that the way forward here is to implement a quick-and-dirty version of https://github.com/RedHat-UX/red-hat-design-system/issues/868 for ux-dot only, taking care to try and make the custom element apis the same as what the official component will be eventually, that would unblock this pr without requiring us to have all our ducks in a row wrt input elements

**Comment by bennypowers** [comment]
@coreyvickery no longer blocked by search as i rolled my own in docs/js/uxdot-search.js. still blocked on https://github.com/patternfly/patternfly-elements/pull/2525, but i have a soft fix in this pr via patch-package. keep in mind that i improvised the design for the combobox

@hellogreg are you able to do a usability assessment on this one-off combobox?

**Comment by bennypowers** [comment]
@hellogreg Please take another look at search usability, I think i got the tab behaviour the way you asked.

@coreyvickery docs wise, is there anything blocking this, asides from image content? keep in mind that any of the content in the listing should be updated in the tokens repo in a separate PR.

**Comment by hellogreg** [comment]
**FACE issue in Mac Safari and Chrome with VoiceOver**

**Summary:** When VoiceOver is on, I'm unable to navigate autocomplete entries for the search input via the arrow keys.

Notes:
- Have not yet tested Windows screen readers.
- Autocomplete entries do not populate at all in Mac Firefox.

To reproduce:
1. First, ensure [Keyboard navigation is on](https://support.apple.com/guide/mac-help/use-your-keyboard-like-a-mouse-mchlp1399/mac) for your Mac. 
2. Optional: In the Advanced tab of Safari Settings, check to see if the "Press Tab to highlight each item on a webpage" box is checked. (If so, you can use Tab to navigate interactive elements on the page. Otherwise, you'll have to use Option-Tab.)
3. Go to the [Tokens demo page](https://deploy-preview-717--red-hat-design-system.netlify.app/tokens/) in Safari/Chrome.
4. Turn on VoiceOver. (Make sure you do not have speech muted, which some people do for testing. This setting is in the Speech section of VoiceOver Utility.)
5. Navigate to the search input.
6. Start typing something that will populate the autocomplete (e.g., "color").
7. Press the down arrow.

**Expected behavior:** The down arrow lets you start selecting autocomplete items in the input.

**Actual behavior:** Focus moves down the page to another region altogether.

**Comment by hellogreg** [comment]
**Select and focus order issues when tabbing from autocomplete options**

**Browsers tested:** Mac Chrome (114) / Firefox (114) / Safari (16.5.1)

**Summary:** After highlighting an autocomplete option with the arrow keys, pressing Tab behaves differently in all browsers.

**To reproduce:**
1. In the browser of your choice, go to the [Tokens demo page](https://deploy-preview-717--red-hat-design-system.netlify.app/tokens/) in Safari/Chrome.
2. Navigate to the search input.
3. Start typing something that will populate the autocomplete (e.g., "color").
4. Arrow down until an option is selected.
5. Press the Tab key.

**Expected behavior:** The autocomplete list closes, the selected item is reflected in the text input box, and focus moves to the next interactive item on the page: the Search button. (This is what happens with the [UK.gov autocomplete](https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-autocomplete-list/) and the [WAI APG example](https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-autocomplete-list/))

**Actual behavior:**
- In Chrome, focus returns to the text input box.
- In Safari, focus moves to the next autocomplete option in the list.
- In Firefox, focus moves to the Introduction heading.

**Comment by bennypowers** [comment]
@hellogreg PTAL

**Comment by hellogreg** [comment]
> @hellogreg PTAL

**Tabbing issue**
Looks like the tabbing issue is fixed! When pressing tab, the input now populates with the selected value (if any) and moves focus to the Search button.

This has now surfaced (created?) another issue. When pressing the Search Button via mouse click or keyboard press, the form is not submitting for me. Instead, the autocomplete list pops back open. I can make another comment on repro-ing this, if you don't see it yourself.

**Safari/VoiceOver issue**
The Safari/VoiceOver issue is still happening. 

Unfortunately, I think there are some bugs with Safari/VoiceOver (judging by WebKit [issue 167671](https://bugs.webkit.org/show_bug.cgi?id=167671) and [issue 209076](https://bugs.webkit.org/show_bug.cgi?id=209076)) that may make this difficult to remedy.

I checked the [WAI APG](https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-autocomplete-list/) and [UK.gov autocomplete](https://alphagov.github.io/accessible-autocomplete/examples/form.html) examples, as well, to see how they fare. Spoiler: the UK.gov version found a way to work, despite the WebKit bugs.

I've also tested these sites in Windows with Firefox/NVDA and Chrome/JAWS. Here are the results:

**Mac Safari/VoiceOver**
- RHDS: Arrows don't cycle through list items. (Fail)
- WAI APG: Buggy. Arrows don't consistently cycle through list items and don't read item values. (Fail)
- UK.gov: Arrows do cycle through all list items. (Success)

**Windows Chrome/JAWS**
- RHDS: Arrows only go to first list item, then stop. (Fail)
- WAI APG: Arrows do cycle through all list items. (Success)
- UK.gov: Arrows do cycle through all list items. (Success)

**Windows Firefox/NVDA**
- RHDS: Arrows only go to first list item, then stop. (Fail)
- WAI APG: Arrows do cycle through all list items. (Success)
- UK.gov: Arrows do cycle through list items. (Success)

Note: Arrow keys work successfully on all sites in all browsers with screen readers off. So this is a screen reader issue.

I also just tried [Headless UI's autocomplete](https://headlessui.com/react/combobox) in Safari, just out of curiosity. The arrows worked well, but it didn't read out selected values, which also aligns with the WebKit bugs mentioned above.

**Comment by bennypowers** [comment]
@hellogreg are the issues with webkit and windows something we can reasonably address in a follow up PR (bulbasaur) or do you think we need to fix them here before merging?

**Comment by hellogreg** [comment]
Imo, getting the Search button working with keybaord and mouse is the real showstopper for this release, and then we can go. Like you said, we'll still need to address the other screen reader issues as best we can in a follow up PR, though.

**Comment by bennypowers** [comment]
Merging now, let's spin out any leftover usability or design issues into bulbasaur

**Pull request merged**
