### PR TITLE
feat: change crayon tokens to semantic tokens

### LINKED ISSUE #809: [feat] Use semantic color tokens wherever possible
Comb through RHDS repo for use of "crayon colors" or other non-semantic tokens, and replace with semantic tokens.

Referencing: https://github.com/RedHat-UX/red-hat-design-tokens/issues/80

### PR DESCRIPTION
**Pull request by marionnegp**
## What I did

Updated tokens for the following elements:

- [x] accordion
- [x] alert
- [x] avatar
- [x] badge
- [x] blockquote
- [x] button
- [x] call to action
- [x] context provider
- [x] dialog
- [x] footer
- [x] navigation secondary
- [x] pagination
- [x] spinner
- [x] statistic
- [x] subnav
- [x] tabs
- [x] tag
- [x] tooltip

## Testing Instructions
Links to deploy previews:

- [ ] [accordion](https://deploy-preview-869--red-hat-design-system.netlify.app/elements/accordion/demo/color-context/)
- [ ] [alert](https://deploy-preview-869--red-hat-design-system.netlify.app/elements/alert/demo/)
- [ ] [avatar](https://deploy-preview-869--red-hat-design-system.netlify.app/elements/avatar/demo/color-context/)
- [x] [badge](https://deploy-preview-869--red-hat-design-system.netlify.app/elements/badge/demo/)
- [ ] [blockquote](https://deploy-preview-869--red-hat-design-system.netlify.app/elements/blockquote/demo/)
- [ ] [button](https://deploy-preview-869--red-hat-design-system.netlify.app/elements/button/demo/color-context/)
- [ ] [call to action](https://deploy-preview-869--red-hat-design-system.netlify.app/elements/call-to-action/demo/)
- [ ] [context provider](https://deploy-preview-869--red-hat-design-system.netlify.app/elements/context-provider/demo/)
- [ ] [dialog](https://deploy-preview-869--red-hat-design-system.netlify.app/elements/dialog/demo/)
- [ ] [footer](https://deploy-preview-869--red-hat-design-system.netlify.app/elements/footer/demo/)
- [ ] navigation secondary broke due to a regression see #874 
- [ ] [pagination](https://deploy-preview-869--red-hat-design-system.netlify.app/elements/pagination/demo/)
- [ ] [spinner](https://deploy-preview-869--red-hat-design-system.netlify.app/elements/spinner/demo/)
- [ ] [statistic](https://deploy-preview-869--red-hat-design-system.netlify.app/elements/statistic/demo/)
- [x] [subnav](https://deploy-preview-869--red-hat-design-system.netlify.app/elements/subnav/demo/color-context/)
- [x] [tabs](https://deploy-preview-869--red-hat-design-system.netlify.app/elements/tabs/demo/color-context/)
- [x] [tag](https://deploy-preview-869--red-hat-design-system.netlify.app/elements/tag/demo/)
- [ ] [tooltip](https://deploy-preview-869--red-hat-design-system.netlify.app/elements/tooltip/demo/)

## Notes to Reviewers
Closes #809

### CODE REVIEW

**Review by bennypowers — COMMENTED** [review]
I released tokens beta.18, so please update here.

Please also take a look over there at tokens, if everything's good to go, we can release 1.0

**Comment by marionnegp** [comment]
@bennypowers, I found one change to the semantic gray tokens (https://github.com/RedHat-UX/red-hat-design-tokens/pull/86), but the rest of that release looks good to me. I was also able to update to the beta.18 for this PR.

**Comment by marionnegp** [comment]
@zeroedin, in rh-navigation-secondary-overlay.css, the `:host` is set to `background: rgb(21, 21, 21, 0.75)`. Would you want that converted to tokens? To make this work, it would have to be done like the play button, which does this:

```
--_g9: var(--rh-color-gray-90-rgb, 21 21 21);
--_play-background-color: rgb(var(--_g9) / var(--rh-opacity-50, 50%));
```

**Comment by marionnegp** [comment]
@bennypowers, this may be a dumb question, but would using the `--rh-color-brand-red` tokens be preferable to using the crayon red tokens?

**Comment by zeroedin** [comment]
> To make this work, it would have to be done like the play button,

That works for me.

**Comment by bennypowers** [comment]
Let's try to merge this urgently so that tokens 1.0 release (tmrw 🤞doesn't require any code changes here

**Review by bennypowers — APPROVED** [review]
We need this merged to unblock other work needed prior to release. Please continue to review and open issues for anything found broken

**Pull request merged**
