### PR TITLE
docs: new footer docs

### PR DESCRIPTION
**Pull request by bennypowers**
## What I did

1. [x] Implement new information architecture (IA) for element pages
2. [x] Add a new top level menu item "Elements"
3. [x] Redirect `/components/footer/*` to `/elements/footer/*`
4. [x] Do same for demos

## Testing Instructions

1. Check out the [DP](https://deploy-preview-638--red-hat-design-system.netlify.app/elements/footer/)
2. [Basic demo](https://deploy-preview-638--red-hat-design-system.netlify.app/elements/footer/demo/) should work
3. [Nested demo](https://deploy-preview-638--red-hat-design-system.netlify.app/elements/footer/demo/global-footer/) should work
4. [Accordion demo](https://deploy-preview-638--red-hat-design-system.netlify.app/components/accordion/demo/) should work
3. [Accordion Nested demo](https://deploy-preview-638--red-hat-design-system.netlify.app/components/accordion/demo/color-context/) should work
5. [/components/footer/](https://deploy-preview-638--red-hat-design-system.netlify.app/components/footer/) should redirect to /elements/footer/
6. [/components/footer/demo/](https://deploy-preview-638--red-hat-design-system.netlify.app/components/footer/demo/) should redirect to /elements/footer/demo/ and work
7. [/components/accordion/](https://deploy-preview-638--red-hat-design-system.netlify.app/components/accordion/) should not redirect (for a subsequent PR)
3. [/components/accordion/demo/](https://deploy-preview-638--red-hat-design-system.netlify.app/components/accordion/demo/) should not redirect (for a subsequent PR)
## Notes to Reviewers
**NB**: :point_right: This PR begins a process of moving all the content in `/components/` to either `/elements/` or `/patterns/` :point_left: 

Element pages are now located at `/elements/${tagName}/` instead of `/components/${tagName}/`. This is in anticipation of `/patterns/${patternName}` TBD. As well, content for element pages is moved from `/docs/components/footer.njk` to `/elements/rh-footer/docs/*.md`

### CODE REVIEW

**Review by zeroedin — COMMENTED** [review]
Looks like the overflow icons for `rh-subnav` aren't loading, returning 404 for `/assets/icons/fas/angle-left.js` and `/assets/icons/fas/angle-right.js`

**Comment by zeroedin** [comment]
> This PR begins a process of moving all the content in /components/ to either /elements/ or /patterns/ 👈

Is there a reason to move away from the `components` nomenclature for `elements` instead?  Or is it mainly about matching the directory structure in dev <-> docs?

**Comment by zeroedin** [comment]
> Looks like the overflow icons for `rh-subnav` aren't loading, returning 404 for `/assets/icons/fas/angle-left.js` and `/assets/icons/fas/angle-right.js`

Would adding an `addPassthroughCopy()` to `eleventy.conf.cjs` be enough here?

```Suggestion
  /* Copy over PatternFly Elements icons */
  eleventyConfig.addPassthroughCopy({ 'node_modules/@patternfly/elements/pf-icon/icons/fas/*': 'assets/icons/fas' });
  eleventyConfig.addPassthroughCopy({ 'node_modules/@patternfly/elements/pf-icon/icons/fab/*': 'assets/icons/fab' });
  eleventyConfig.addPassthroughCopy({ 'node_modules/@patternfly/elements/pf-icon/icons/far/*': 'assets/icons/far' });
  eleventyConfig.addPassthroughCopy({ 'node_modules/@patternfly/elements/pf-icon/icons/patternfly/*': 'assets/icons/patternfly' });
```
Seems to work, trying to figure out any negatives to this approach...

**Comment by bennypowers** [comment]
> > This PR begins a process of moving all the content in /components/ to either /elements/ or /patterns/ 👈
> 
> Is there a reason to move away from the `components` nomenclature for `elements` instead? Or is it mainly about matching the directory structure in dev <-> docs?

From above

> This is in anticipation of /patterns/${patternName} TBD.

"Components" is an overloaded term on it current docs, which includes both elements and patterns. Since our output is tokens, (custom) elements, and patterns (and docs for each), wouldn't it be better to specify which were talking about, so that everyone's on the same page?

**Comment by coreyvickery** [comment]
@bennypowers Seems like styles are shifting a bit when placed on ux dot.

Steven's original DP:
Screen Shot 2023-03-09 at 7 15 58 AM
https://deploy-preview-718--red-hat-design-system.netlify.app/components/subnav/demo/

Benny's DP:
Screen Shot 2023-03-09 at 7 16 08 AM

Style specs:
https://xd.adobe.com/view/9aeac027-7f86-4245-bad0-58022954fcd5-cfb9/screen/086bd62d-666a-4ef7-a2fa-aa8ab6f5a19b/specs/

**Comment by zeroedin** [comment]
> @bennypowers Seems like styles are shifting a bit when placed on ux dot.

@coreyvickery check again, there was an issue in `rh-subnav` that was corrected and merged this morning.  I updated this branch with main, and now the styles should look correct.

**Comment by bennypowers** [comment]
> Looks like the overflow icons for `rh-subnav` aren't loading, returning 404 for `/assets/icons/fas/angle-left.js` and `/assets/icons/fas/angle-right.js`

This might be a problem in BaseIcon's `load` method, or perhaps in how it is emitted via esbuild and tsc? I had a similar problem on the israel marketting site and this was the hacky solution: https://github.com/RedHat-Israel/RedHat-Israel.github.io/commit/08d48e1b9353ced1176533023670cd86bbd63ed8

**Comment by coreyvickery** [comment]
> > @bennypowers Seems like styles are shifting a bit when placed on ux dot.
> 
> @coreyvickery check again, there was an issue in `rh-subnav` that was corrected and merged this morning. I updated this branch with main, and now the styles should look correct.

@zeroedin @bennypowers Styles look correct, but the type size is too big. Let's knock it down to 16px if possible.

**Comment by zeroedin** [comment]
> @zeroedin @bennypowers Styles look correct, but the type size is too big. Let's knock it down to 16px if possible.

Looks like the 18px font is coming from this style here.  Here I thought we nuked all scss 👀  🙃 😆 
https://github.com/RedHat-UX/red-hat-design-system/blob/c570474ad6ddfaeb56c37b105a02b9e7b3c2e461/docs/scss/_base/_base.scss#L44

**Comment by bennypowers** [comment]
> Here I thought we nuked all scss 👀  🙃 😆 

Only in elements. If you'd ask me, I'd say we're overdue to refactor the page CSS:
- remove SCSS
- remove BEM-style selectors
- tokens everywhere
- maybe adopt Declarative Shadow DOM on ux-dot
  - [Mozilla's support for the feature is now positive](https://bugzilla.mozilla.org/show_bug.cgi?id=1712140)
  - [WebKit shipped it](https://github.com/WebKit/WebKit/pull/7798)
  - we'd apply the polyfill and use an 11ty transform to stamp custom elements with DSD templates 
  - we'd show other teams it's possible

The advantages we stand to gain are: 
- smaller node_modules
- fewer dependencies
- faster builds
- easier to grok CSS
- more dogfooding
- provide an examplary use of RHDS tech

**Comment by bennypowers** [comment]
> > > @bennypowers Seems like styles are shifting a bit when placed on ux dot.
> > 
> > 
> > @coreyvickery check again, there was an issue in `rh-subnav` that was corrected and merged this morning. I updated this branch with main, and now the styles should look correct.
> 
> @zeroedin @bennypowers Styles look correct, but the type size is too big. Let's knock it down to 16px if possible.

fixed

**Comment by zeroedin** [comment]
@bennypowers  @coreyvickery Thoughts on maybe offering an optional `rh-subnav-lightdom.css`?  

After playing with the demos there is quite a bit of layout bounce on load given `rh-subnav` is above the fold. This is a good reason/time to add some lightdom CSS that can be loaded optionally although even optionally is most likely *recommended* as `rh-subnav` use case is most likely always above the fold.

**Review by zeroedin — APPROVED** [review]
Lazily Giving This Message

**Pull request merged**
