### PR TITLE
fix(tile): tile headline size

### PR DESCRIPTION
**Pull request by markcaron**
## What I did

1. Fixed the headline, title, body text, and footer font-sizes to match the [Tile specs](https://www.figma.com/design/8cZsqpCsq3KyiHf5VyBuRO/Element---Tile?node-id=507-2284&m=dev) for both the default and compact variants.

## Testing Instructions

1. Inspect the font-sizes of the headlines, title, body, and footer in the demos and ensure they match both variants in the spec.
2. Dev: check that my CSS looks good too, and that there should be no repercussions (e.g., with my `!important` flags).

Closes: #1591

### CODE REVIEW

**Comment by markcaron** [comment]
CC: @OneEightyFirst — FYI. We're fixing the Tile heading sizes. LMK if you think this will mess up anything on the implementation side.

**Review by zeroedin — CHANGES_REQUESTED** [review]
Needs a changeset

**Review by zeroedin — APPROVED** [review]
Laying Grout Tile Mosaics

**Review by marionnegp — CHANGES_REQUESTED** [review]
I'm still seeing the heading being bolder than it should be:
Screenshot 2024-07-10 at 9 59 26 AM
Screenshot 2024-07-10 at 9 59 11 AM

Should be `var(--rh-font-weight-body-text-medium, 500)`

Is it Netifly/UX dot styles interfering?

**Comment by markcaron** [comment]
@marionnegp it is picking up the heavier weight (700) from ux dot styles. Will fix

**Comment by zeroedin** [comment]
> 
> Should be `var(--rh-font-weight-body-text-medium, 500)`
> 
> Is it Netifly/UX dot styles interfering?

Looks like we need to add an `!important` to the font-weight as well:

https://github.com/RedHat-UX/red-hat-design-system/blob/aa02acbffe418dab434280ba0281f29ebe48ad86/elements/rh-tile/rh-tile.css#L38

```
font-weight: var(--rh-font-weight-heading-medium, 500) !important;
```

**Review by marionnegp — APPROVED** [review]
Lowbrow Gibberish, Toddlers Mimic

**Comment by bennypowers** [comment]
> Lowbrow Gibberish, Toddlers Mimic

funny *and* topical. 10 points

**Pull request merged**
