### PR TITLE
docs: fix repoStatus naming convention

### PR DESCRIPTION
**Pull request by zeroedin**
## What I did

1.  Align components names to match the naming convention used in the subnav.
2.  Fixes missing rh-tag's in subnav when a component is still in planning.

## Testing Instructions

1.

### CODE REVIEW

**Review by bennypowers — COMMENTED** [review]
We have utilities to convert from tagname to slug to pretty alias

Feels like this table- or parts of it- should be a function call

**Comment by zeroedin** [comment]
> We have utilities to convert from tagname to slug to pretty alias
> 
> Feels like this table- or parts of it- should be a function call

Can we split that off to a different issue.  This resolves the problem for the immediate.

**Review by adamjohnson — APPROVED** [review]
The guidelines are an awesome addition 👏 

Links Get Tagged (with) Meaning

**Comment by adamjohnson** [comment]
Related to #1734.

**Pull request merged**
